version: "3.8"

services:
  # GOLANG API
  celer-api:
    build: 
      context: "./backend-golang/"
      dockerfile: Dockerfile
    image: e-rivas/celer-golang-backend:v0.0.1
    container_name: celer-api
    volumes:
      - "./backend-golang/:/backend-golang"
      - "./.env:/backend-golang/.env"
    environment:
      - DEBUG=true
      - DB_USER=${API_DB_USER}
      - DB_PASSWORD=${API_DB_PASSWORD}
      - DB_NAME=${API_DB_NAME}
      - DB_HOST=${API_DB_HOST}
      - DB_PORT=${API_DB_PORT}
      - DB_URI=${API_DB_URI}
      - BASE_PATH=${BASE_PATH}
      - ADDR=${ADDR}
      - CAMUNDA_BASE_URL=${CAMUNDA_BASE_URL}
    depends_on:
      - postgres-db-api
      - camunda-platform
    ports:
      - "5000:5000"
    networks:
      - main

  # CELER FRONT
  celer-angular:
    build: 
      context: "./frontend-angular/"
      dockerfile: Dockerfile
    image: e-rivas/celer-angular-front:v0.0.1
    container_name: celer-angular
    volumes:
      - "./frontend-angular/:/frontend-angular/"
    depends_on:
      - celer-api
      - camunda-platform
    ports:
      - "4200:4200"
    networks:
      - main


  # POSTGRES DB - USED BY API
  postgres-db-api:
    image: postgres:14.2-alpine
    container_name: celer-db-api-postgres
    restart: always
    environment:
      - "POSTGRES_USER=${API_DB_USER}"
      - "POSTGRES_PASSWORD=${API_DB_PASSWORD}"
      - "POSTGRES_DB=${API_DB_NAME}"
      - "POSTGRES_PORT=${API_DB_PORT}"
    ports:
      - "5432:5432"
    volumes:
      - "./docker-volumes/backend/postgres/data:/var/lib/postgresql/data"
    networks:
      - main

  # WORKFLOW ENGINE - USED BY API
  camunda-platform:
    image: camunda/camunda-bpm-platform:run-7.17.0-SNAPSHOT
    command: ./camunda.sh --rest --swaggerui --webapps
    container_name: celer-camunda-platform
    environment:
      - "DB_DRIVER=org.postgresql.Driver"
      - "DB_URL=jdbc:postgresql://postgres-db-camunda:5432/${CAMUNDA_DB_NAME}"
      - "DB_USERNAME=${CAMUNDA_DB_USER}"
      - "DB_PASSWORD=${CAMUNDA_DB_PASSWORD}"
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - "./docker-volumes/workflow-engine/camunda/webapps/:/camunda/webapps/"
    links:
      - postgres-db-camunda
    depends_on:
      - postgres-db-camunda
    networks:
      - main

  # POSTGRES DB - USED BY WORKFLOW ENGINE
  postgres-db-camunda:
    image: postgres:14.2-alpine
    restart: always
    container_name: celer-db-camunda-postgres
    environment:
      - "POSTGRES_USER=${CAMUNDA_DB_USER}"
      - "POSTGRES_PASSWORD=${CAMUNDA_DB_PASSWORD}"
      - "POSTGRES_DB=${CAMUNDA_DB_NAME}"
    ports:
      - "5032:5432"
    volumes:
      - "./docker-volumes/workflow-engine/postgres/data:/var/lib/postgresql/data"
    networks:
      - main

networks:
  main:
    driver: bridge
