version: "3.8"

services:
  # Camunda platform with zeebe embeeded (I guess)
  camunda-platform:
    image: camunda/camunda-bpm-platform:7.18.0-SNAPSHOT
    container_name: celer-camunda-platform
    environment:
      - "DB_DRIVER=org.postgresql.Driver"
      - "DB_URL=jdbc:postgresql://postgres:5432/camunda"
      - "DB_USERNAME=camunda"
      - "DB_PASSWORD=camunda"
      # - 'WAIT_FOR=postgres:5432'
      # - DEBUG=true
    links:
      - postgres
    ports:
      - "8080:8080"
      # - "8000:8000" DEBUG
    restart: unless-stopped
    networks:
      - camunda
    depends_on:
      - postgres
    #volumes:
    #  - "./camunda-platform/config:/camunda/conf"

  postgres:
    image: postgres:14.2-alpine
    container_name: celer-camunda-db
    restart: always
    environment:
      - "POSTGRES_USER=camunda"
      - "POSTGRES_PASSWORD=camunda"
      - "POSTGRES_DB=camunda"
    ports:
      - "5032:5432"
    networks:
      - camunda
    #volumes:
    #  - './postgres/data:/var/lib/postgresql/data'

networks:
  camunda:
    driver: bridge
