version: "3.8"

services:
  # Camunda platform with zeebe embeeded (I guess)
  camunda-platform:
    image: camunda/camunda-bpm-platform:7.18.0-SNAPSHOT
    command: ./camunda.sh --rest --swaggerui --webapps
    container_name: celer-camunda-platform
    environment:
      - "DB_DRIVER=org.postgresql.Driver"
      - "DB_URL=jdbc:postgresql://postgres:5432/${DB_NAME}"
      - "DB_USERNAME=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      # - DEBUG=true
    links:
      - postgres
    ports:
      - "8080:8080"
      # - "8000:8000" DEBUG
    restart: unless-stopped
    networks:
      - camunda
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2-alpine
    container_name: celer-camunda-db
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - "5032:5432"
    networks:
      - camunda
    #volumes:
    #  - './postgres/data:/var/lib/postgresql/data'

networks:
  camunda:
    driver: bridge
