version: "3.8"

services:
  # Camunda platform with zeebe embeeded (I guess)
  camunda-platform:
    image: camunda/camunda-bpm-platform:run-7.17.0-SNAPSHOT
    command: ./camunda.sh --rest --swaggerui --webapps
    container_name: celer-camunda-platform
    environment:
      - "DB_DRIVER=org.postgresql.Driver"
      - "DB_URL=jdbc:postgresql://postgres:5432/${DB_NAME}"
      - "DB_USERNAME=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
    links:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - camunda
    depends_on:
      - postgres
    volumes:
    - '$PWD/webapps/:/camunda/webapps/'

  postgres:
    image: postgres:14.2-alpine
    container_name: celer-camunda-db
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - "5032:5432"
    networks:
      - camunda

networks:
  camunda:
    driver: bridge
