version: '3.8'
services:
  postgres-db:
    image: postgres:14.2-alpine
    container_name: celer-postgres
    restart: always
    environment:
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_NAME}'
    ports:
      - '5432:5432'
    volumes:
      - './postgres/data:/var/lib/postgresql/data'

volumes:
  postgres-db:
    driver: local